### ISSUE TITLE
git commit plus single quotes leads to errors on some Windows shells

### ISSUE THREAD

**Issue by paulproteus** [chalmerlowe/intro_to_sprinting#110] opened 2017-05-22 02:10 UTC

**Comment by seawolf42** [comment] 2017-08-05 21:35
@paulproteus good point. We should probably change all single quotes to double quotes throughout all the bash code blocks, *or* write something up about it early. @chalmerlowe do you have a preference? The former is more work but probably also alleviates more questions during the class.

**Comment by paulproteus** [comment] 2017-08-05 21:44
I would vote for double-quotes, plus the contribution of a `STYLEGUIDE.md` which explains this chcoice, as well as as a travis-ci script that checks that we never violate this in the future.

If you do the first two, I'll volunteer to do to the travis-ci automation!

**Comment by chalmerlowe** [comment] 2017-08-05 21:51
I am fine with double quotes in bash code blocks.
the styleguide.md idea is also quite good.

**Comment by seawolf42** [comment] 2017-08-05 22:14
OK, it's now got the 'help wanted' tag... hopefully some brave soul will pick this up. 😄

**Comment by chalmerlowe** [comment] 2019-04-13 08:02
@seawolf42 looks like this can be closed.

**Comment by seawolf42** [comment] 2019-04-13 21:41
confirmed all of these have been previously addressed, closing

**Closed by seawolf42** 2019-04-13 21:41 UTC
Labels: enhancement, help wanted
